language: java
before_install:
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://dl.google.com/android/android-sdk_r22.0.1-linux.tgz
  - tar -zxf android-sdk_r22.0.1-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo y | android update sdk --filter 1,2,3,5,32,64 --no-ui --force -a
  - echo no | android create avd --force -n test -t android-17 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
before_script:
  - ./wait-for-emulator
script: mvn install -Pintegration-tests -Dandroid.device=test
