language: java
before_install:
  - wget http://dl.google.com/android/android-sdk_r22.0.1-linux.tgz
  - tar -zxf android-sdk_r22.0.1-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo y | android update sdk -t 1,2,3,5,43,extra -u -f -a -s
  - git clone https://github.com/ccl1115/maven-android-sdk-deployer.git maven-android-sdk-deployer
  - cd maven-android-sdk-deployer
  - mvn install -P 4.2,r4
  - cd ..
script: gradle build

